// All animated icons from the official lucide-animated package.
// CrownIcon is aliased to ChessKingIcon (the intended premium/leaderboard icon).
// LogInIcon has no lucide-animated equivalent — kept as a minimal custom file.
// RefreshCCW/CW and RotateCCW are aliased from their camelCase exports.
export {
  ActivityIcon,         type ActivityIconHandle,
  ArrowDownIcon,        type ArrowDownIconHandle,
  ArrowLeftIcon,        type ArrowLeftIconHandle,
  ArrowRightIcon,       type ArrowRightIconHandle,
  ArrowUpIcon,          type ArrowUpIconHandle,
  BadgeAlertIcon,       type BadgeAlertIconHandle,
  BanIcon,              type BanIconHandle,
  BellIcon,             type BellIconHandle,
  BellElectricIcon,     type BellElectricIconHandle,
  BoldIcon,             type BoldIconHandle,
  BookmarkIcon,         type BookmarkIconHandle,
  BookmarkCheckIcon,    type BookmarkCheckIconHandle,
  BookmarkPlusIcon,     type BookmarkPlusIconHandle,
  BriefcaseBusinessIcon,type BriefcaseBusinessIconHandle,
  CalendarDaysIcon,     type CalendarDaysIconHandle,
  CheckIcon,            type CheckIconHandle,
  CheckCheckIcon,       type CheckCheckIconHandle,
  ChessKingIcon as CrownIcon, type ChessKingIconHandle as CrownIconHandle,
  ChevronDownIcon,      type ChevronDownIconHandle,
  ChevronLeftIcon,      type ChevronLeftIconHandle,
  ChevronRightIcon,     type ChevronRightIconHandle,
  ChevronUpIcon,        type ChevronUpIconHandle,
  CircleCheckIcon,      type CircleCheckIconHandle,
  CircleHelpIcon,       type CircleHelpIconHandle,
  ClockIcon,            type ClockIconHandle,
  ContrastIcon,         type ContrastIconHandle,
  CopyIcon,             type CopyIconHandle,
  DeleteIcon,           type DeleteIconHandle,
  DownloadIcon,         type DownloadIconHandle,
  DownvoteIcon,         type DownvoteIconHandle,
  ExpandIcon,           type ExpandIconHandle,
  EyeIcon,              type EyeIconHandle,
  EyeOffIcon,           type EyeOffIconHandle,
  FilePenLineIcon,      type FilePenLineIconHandle,
  FileTextIcon,         type FileTextIconHandle,
  FlameIcon,            type FlameIconHandle,
  GalleryThumbnailsIcon,type GalleryThumbnailsIconHandle,
  GraduationCapIcon,    type GraduationCapIconHandle,
  GripHorizontalIcon,   type GripHorizontalIconHandle,
  GripVerticalIcon,     type GripVerticalIconHandle,
  HistoryIcon,          type HistoryIconHandle,
  HomeIcon,             type HomeIconHandle,
  IdCardIcon,           type IdCardIconHandle,
  ItalicIcon,           type ItalicIconHandle,
  LayoutPanelTopIcon,   type LayoutPanelTopIconHandle,
  LinkIcon,             type LinkIconHandle,
  LoaderIcon,           type LoaderIconHandle,
  LoaderCircleIcon,     type LoaderCircleIconHandle,
  LockIcon,             type LockIconHandle,
  LockOpenIcon,         type LockOpenIconHandle,
  LogoutIcon,           type LogoutIconHandle,
  MailboxIcon,          type MailboxIconHandle,
  MapPinIcon,           type MapPinIconHandle,
  Maximize2Icon,        type Maximize2IconHandle,
  MaximizeIcon,         type MaximizeIconHandle,
  MenuIcon,             type MenuIconHandle,
  MessageCircleIcon,    type MessageCircleIconHandle,
  MessageCircleMoreIcon,type MessageCircleMoreIconHandle,
  MessageCircleXIcon,   type MessageCircleXIconHandle,
  MessageSquareIcon,    type MessageSquareIconHandle,
  MessageSquareMoreIcon,type MessageSquareMoreIconHandle,
  MessageSquareXIcon,   type MessageSquareXIconHandle,
  MinimizeIcon,         type MinimizeIconHandle,
  MoonIcon,             type MoonIconHandle,
  PauseIcon,            type PauseIconHandle,
  PlayIcon,             type PlayIconHandle,
  PlusIcon,             type PlusIconHandle,
  RedoIcon,             type RedoIconHandle,
  RefreshCcwIcon as RefreshCCWIcon, type RefreshCcwIconHandle as RefreshCCWIconHandle,
  RefreshCwIcon  as RefreshCWIcon,  type RefreshCwIconHandle  as RefreshCWIconHandle,
  RotateCcwIcon  as RotateCCWIcon,  type RotateCcwIconHandle  as RotateCCWIconHandle,
  SearchIcon,           type SearchIconHandle,
  SendIcon,             type SendIconHandle,
  SettingsIcon,         type SettingsIconHandle,
  ShieldCheckIcon,      type ShieldCheckIconHandle,
  ShrinkIcon,           type ShrinkIconHandle,
  SmartphoneNfcIcon,    type SmartphoneNfcIconHandle,
  SparklesIcon,         type SparklesIconHandle,
  SquarePenIcon,        type SquarePenIconHandle,
  SquareStackIcon,      type SquareStackIconHandle,
  SunIcon,              type SunIconHandle,
  SwitchCameraIcon,     type SwitchCameraIconHandle,
  TerminalIcon,         type TerminalIconHandle,
  UndoIcon,             type UndoIconHandle,
  UploadIcon,           type UploadIconHandle,
  UpvoteIcon,           type UpvoteIconHandle,
  UserIcon,             type UserIconHandle,
  UserCheckIcon,        type UserCheckIconHandle,
  UsersIcon,            type UsersIconHandle,
  UsersRoundIcon,       type UsersRoundIconHandle,
  XIcon,                type XIconHandle,
  ZapIcon,              type ZapIconHandle,
} from "lucide-animated";

// LogInIcon has no lucide-animated equivalent
export * from "./login";
